import { execSync } from 'node:child_process'
import { writeFileSync, readFileSync, existsSync } from 'node:fs'

interface UpdateServerConfigParams {
  vpnPort: number
  vpnProtocol: 'udp' | 'tcp'
  tunnelMode: 'full' | 'split'
  vpnNetwork: string
  vpnNetmask: string
  dnsServers: string
  customRoutes?: string[]
  enableCompression: boolean
  cipher: string
  keepalivePing: number
  keepaliveTimeout: number
  customServerConfig?: string
}

export async function handleUpdateServerConfig(params: Record<string, unknown>): Promise<Record<string, unknown>> {
  const config = params as unknown as UpdateServerConfigParams

  const CONFIG_PATH = '/etc/openvpn/server/server.conf'
  const BACKUP_PATH = '/etc/openvpn/server/server.conf.backup'

  if (!existsSync(CONFIG_PATH)) {
    throw new Error('OpenVPN server config not found. Please install OpenVPN server first.')
  }

  try {
    // Backup current config
    const currentConfig = readFileSync(CONFIG_PATH, 'utf-8')
    writeFileSync(BACKUP_PATH, currentConfig)
    console.log('[update-config] Backed up current config')

    // Generate new config
    const dnsArray = config.dnsServers.split(',').map(d => d.trim()).filter(Boolean)
    const customRoutes = config.customRoutes || []

    let newConfig = `# OpenVPN Server Configuration
# Generated by OVPN Manager
# Last updated: ${new Date().toISOString()}

port ${config.vpnPort}
proto ${config.vpnProtocol}
dev tun

ca /etc/openvpn/server/ca.crt
cert /etc/openvpn/server/server.crt
key /etc/openvpn/server/server.key
dh /etc/openvpn/server/dh.pem
tls-crypt /etc/openvpn/server/tls-crypt.key

server ${config.vpnNetwork} ${config.vpnNetmask}
topology subnet

# DNS Configuration
`

    dnsArray.forEach(dns => {
      newConfig += `push "dhcp-option DNS ${dns}"\n`
    })

    newConfig += `
# Tunnel Mode: ${config.tunnelMode}
`

    if (config.tunnelMode === 'full') {
      newConfig += `push "redirect-gateway def1 bypass-dhcp"\n`
    } else {
      newConfig += `# Split tunnel - only route specific networks\n`
      customRoutes.forEach(route => {
        newConfig += `push "route ${route}"\n`
      })
    }

    newConfig += `
# Connection Settings
keepalive ${config.keepalivePing} ${config.keepaliveTimeout}
cipher ${config.cipher}
persist-key
persist-tun
`

    if (config.enableCompression) {
      newConfig += `compress lz4-v2\npush "compress lz4-v2"\n`
    }

    newConfig += `
# Drop privileges (comment out if you have permission issues)
user nobody
group nogroup

# Logging
status /var/log/openvpn/status.log
log /var/log/openvpn/openvpn.log
verb 3
`

    // Add custom server config if provided
    if (config.customServerConfig) {
      newConfig += `\n# Custom Configuration\n${config.customServerConfig}\n`
    }

    // Write new config
    writeFileSync(CONFIG_PATH, newConfig)
    console.log('[update-config] Wrote new config')

    // Reload OpenVPN service
    try {
      execSync('systemctl restart openvpn-server@server.service 2>/dev/null || systemctl restart openvpn@server.service', {
        stdio: 'pipe'
      })
      console.log('[update-config] Restarted OpenVPN service')
    } catch (err) {
      console.error('[update-config] Failed to restart service:', err)
      // Restore backup
      writeFileSync(CONFIG_PATH, currentConfig)
      throw new Error('Failed to restart OpenVPN service. Config restored from backup.')
    }

    // Wait a moment and check if service is running
    await new Promise(resolve => setTimeout(resolve, 2000))

    try {
      execSync('systemctl is-active openvpn-server@server.service 2>/dev/null || systemctl is-active openvpn@server.service', {
        stdio: 'pipe'
      })
    } catch (err) {
      // Service not running, restore backup
      writeFileSync(CONFIG_PATH, currentConfig)
      execSync('systemctl restart openvpn-server@server.service 2>/dev/null || systemctl restart openvpn@server.service', {
        stdio: 'pipe'
      })
      throw new Error('OpenVPN service failed to start with new config. Restored previous config.')
    }

    return {
      success: true,
      message: 'Server configuration updated successfully',
      configPath: CONFIG_PATH,
      backupPath: BACKUP_PATH
    }
  } catch (error: any) {
    console.error('[update-config] Error:', error.message)
    throw new Error(`Failed to update server config: ${error.message}`)
  }
}
