import { execSync } from 'node:child_process'
import { writeFileSync, readFileSync, existsSync } from 'node:fs'
import type { VpnDriver } from '../drivers'

interface UpdateServerConfigParams {
  vpnPort: number
  vpnProtocol: 'udp' | 'tcp'
  tunnelMode: 'full' | 'split'
  vpnNetwork: string
  vpnNetmask: string
  dnsServers: string
  customRoutes?: string[]
  enableCompression: boolean
  cipher: string
  keepalivePing: number
  keepaliveTimeout: number
  customServerConfig?: string
}

export async function handleUpdateServerConfig(params: Record<string, unknown>, driver: VpnDriver): Promise<Record<string, unknown>> {
  const config = params as unknown as UpdateServerConfigParams

  const CONFIG_PATH = '/etc/openvpn/server/server.conf'
  const BACKUP_PATH = '/etc/openvpn/server/server.conf.backup'

  if (!existsSync(CONFIG_PATH)) {
    throw new Error('VPN server config not found. Please install VPN server first.')
  }

  try {
    // Backup current config
    const currentConfig = readFileSync(CONFIG_PATH, 'utf-8')
    writeFileSync(BACKUP_PATH, currentConfig)
    console.log('[update-config] Backed up current config')

    // Generate new config
    const dnsArray = config.dnsServers.split(',').map(d => d.trim()).filter(Boolean)
    const customRoutes = config.customRoutes || []

    let newConfig = `# VPN Server Configuration
# Generated by VPN Manager
# Last updated: ${new Date().toISOString()}

port ${config.vpnPort}
proto ${config.vpnProtocol}
dev tun

ca /etc/openvpn/server/ca.crt
cert /etc/openvpn/server/server.crt
key /etc/openvpn/server/server.key
dh none
tls-crypt /etc/openvpn/server/tls-crypt.key

server ${config.vpnNetwork} ${config.vpnNetmask}
topology subnet

# DNS Configuration
`

    dnsArray.forEach(dns => {
      newConfig += `push "dhcp-option DNS ${dns}"\n`
    })

    newConfig += `
# Tunnel Mode: ${config.tunnelMode}
`

    if (config.tunnelMode === 'full') {
      newConfig += `push "redirect-gateway def1 bypass-dhcp"\n`
    } else {
      newConfig += `# Split tunnel - only route specific networks\n`
      customRoutes.forEach(route => {
        newConfig += `push "route ${route}"\n`
      })
    }

    newConfig += `
# Connection Settings
keepalive ${config.keepalivePing} ${config.keepaliveTimeout}
cipher ${config.cipher}
ncp-ciphers ${config.cipher}
auth SHA256
tls-server
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
persist-key
persist-tun
`

    if (config.enableCompression) {
      newConfig += `compress lz4-v2\npush "compress lz4-v2"\n`
    }

    newConfig += `
# Drop privileges (comment out if you have permission issues)
user nobody
group nogroup

# Management Interface (bind to 0.0.0.0 for Docker access)
management 0.0.0.0 7505
management-client-auth

# Logging
status /var/log/openvpn/status.log
status-version 3
log /var/log/openvpn/openvpn.log
verb 3

script-security 2

# VPN Hooks (Certificate-only authentication)
client-connect /usr/local/bin/vpn-connect
client-disconnect /usr/local/bin/vpn-disconnect
`

    // Add custom server config if provided
    if (config.customServerConfig) {
      newConfig += `\n# Custom Configuration\n${config.customServerConfig}\n`
    }

    // Write new config
    writeFileSync(CONFIG_PATH, newConfig)
    console.log('[update-config] Wrote new config')

    // Reload VPN via management interface
    try {
      await driver.sendCommand('signal SIGHUP')
      console.log('[update-config] Reloaded VPN via management interface')
    } catch (err) {
      console.error('[update-config] Failed to reload via management interface:', err)
      // Restore backup
      writeFileSync(CONFIG_PATH, currentConfig)
      throw new Error('Failed to reload VPN. Config restored from backup.')
    }

    // Wait a moment for reload to complete
    await new Promise(resolve => setTimeout(resolve, 2000))

    // Verify VPN is still connected
    if (!driver.isConnected()) {
      // Restore backup
      writeFileSync(CONFIG_PATH, currentConfig)
      throw new Error('VPN disconnected after config update. Restored previous config.')
    }

    return {
      success: true,
      message: 'Server configuration updated successfully',
      configPath: CONFIG_PATH,
      backupPath: BACKUP_PATH
    }
  } catch (error: any) {
    console.error('[update-config] Error:', error.message)
    throw new Error(`Failed to update server config: ${error.message}`)
  }
}
