import { writeFileSync, readFileSync, existsSync } from 'node:fs'
import type { VpnDriver } from '../drivers'

interface UpdateServerConfigParams {
  port: number
  protocol: 'udp' | 'tcp'
  tunnel_mode: 'full' | 'split'
  vpn_network: string
  vpn_netmask: string
  dns_servers: string
  push_routes?: string
  compression: string
  cipher: string
  keepalive_ping: number
  keepalive_timeout: number
}

export async function handleUpdateServerConfig(params: Record<string, unknown>, driver: VpnDriver): Promise<Record<string, unknown>> {
  const config = params as unknown as UpdateServerConfigParams

  const CONFIG_PATH = '/etc/openvpn/server/server.conf'
  const BACKUP_PATH = '/etc/openvpn/server/server.conf.backup'

  if (!existsSync(CONFIG_PATH)) {
    throw new Error('VPN server config not found. Please install VPN server first.')
  }

  // Validate required parameters
  if (!config.vpn_network || !config.vpn_netmask) {
    throw new Error('Missing required parameters: vpn_network, vpn_netmask')
  }

  // Set defaults for optional parameters
  const port = config.port || 1194
  const protocol = config.protocol || 'udp'
  const dnsServers = config.dns_servers || '8.8.8.8,1.1.1.1'
  const tunnelMode = config.tunnel_mode || 'full'
  const cipher = config.cipher || 'AES-256-GCM'
  const keepalivePing = config.keepalive_ping || 10
  const keepaliveTimeout = config.keepalive_timeout || 120
  const enableCompression = config.compression === 'lz4-v2'
  
  // Parse custom routes from push_routes string
  const customRoutes = config.push_routes 
    ? config.push_routes.split(',').map(r => r.trim()).filter(Boolean)
    : []

  try {
    // Backup current config
    const currentConfig = readFileSync(CONFIG_PATH, 'utf-8')
    writeFileSync(BACKUP_PATH, currentConfig)
    console.log('[update-config] Backed up current config')

    // Generate new config
    const dnsArray = dnsServers.split(',').map(d => d.trim()).filter(Boolean)

    let newConfig = `# VPN Server Configuration
# Generated by VPN Manager
# Last updated: ${new Date().toISOString()}

port ${port}
proto ${protocol}
dev tun

ca /etc/openvpn/server/ca.crt
cert /etc/openvpn/server/server.crt
key /etc/openvpn/server/server.key
dh none
tls-crypt /etc/openvpn/server/tls-crypt.key

server ${config.vpn_network} ${config.vpn_netmask}
topology subnet

# DNS Configuration
`

    dnsArray.forEach(dns => {
      newConfig += `push "dhcp-option DNS ${dns}"\n`
    })

    newConfig += `
# Tunnel Mode: ${tunnelMode}
`

    if (tunnelMode === 'full') {
      newConfig += `push "redirect-gateway def1 bypass-dhcp"\n`
    } else {
      newConfig += `# Split tunnel - only route specific networks\n`
      customRoutes.forEach(route => {
        newConfig += `push "route ${route}"\n`
      })
    }

    newConfig += `
# Connection Settings
keepalive ${keepalivePing} ${keepaliveTimeout}
cipher ${cipher}
ncp-ciphers ${cipher}
auth SHA256
tls-server
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
persist-key
persist-tun
`

    if (enableCompression) {
      newConfig += `compress lz4-v2\npush "compress lz4-v2"\n`
    }

    newConfig += `
# Drop privileges (comment out if you have permission issues)
user nobody
group nogroup

# Logging
status /var/log/openvpn/status.log
status-version 3
log /var/log/openvpn/openvpn.log
verb 3

script-security 2

# Management Interface
management /run/openvpn/server.sock unix
`

    // Write new config
    writeFileSync(CONFIG_PATH, newConfig)
    console.log('[update-config] Wrote new config')

    // Reload VPN via management interface
    try {
      await driver.sendCommand('signal SIGHUP')
      console.log('[update-config] Sent SIGHUP signal to OpenVPN')
    } catch (err) {
      console.error('[update-config] Failed to send SIGHUP:', err)
      // Restore backup
      writeFileSync(CONFIG_PATH, currentConfig)
      throw new Error('Failed to reload VPN. Config restored from backup.')
    }

    // Wait for OpenVPN to reload and reconnect
    console.log('[update-config] Waiting for OpenVPN to reload...')
    await new Promise(resolve => setTimeout(resolve, 5000))

    // Note: Don't check driver.isConnected() here because:
    // - OpenVPN will disconnect management socket during reload
    // - Driver will auto-reconnect after reload completes
    // - Checking too early will cause false negative

    return {
      success: true,
      message: 'Server configuration updated successfully. OpenVPN is reloading.',
      configPath: CONFIG_PATH,
      backupPath: BACKUP_PATH,
      note: 'OpenVPN will reconnect automatically after reload completes'
    }
  } catch (error: any) {
    console.error('[update-config] Error:', error.message)
    throw new Error(`Failed to update server config: ${error.message}`)
  }
}
